# Generated by Django 4.1 on 2022-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atracoes", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="atracoes",
            field=models.ManyToManyField(to="atracoes.atracao"),
        ),
    ]
