# Generated by Django 4.1 on 2022-08-31 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pontoturistico_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocIdentificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="pontoturistico",
            name="doc_identificacao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.docidentificacao",
            ),
        ),
    ]
