# Generated by Django 4.1 on 2022-08-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacao",
            old_name="user",
            new_name="usuario",
        ),
    ]
